# Generated by Django 4.2.7 on 2023-12-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
