# Generated by Django 4.2.7 on 2023-12-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0006_alter_audiofile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='display_name',
            field=models.CharField(
                blank=True, default='Default Name', max_length=255, null=True),
        ),
    ]
